# Generated by Django 2.2.4 on 2020-02-24 14:57

from django.db import migrations
import phonenumber_field.modelfields
import phonenumbers

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Нормализированный номер владельца'),
        ),
    ]
