# Generated by Django 2.2.4 on 2020-02-26 09:47

from django.db import migrations
import phonenumbers


def filter_phonenumbers(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')

    for flat in flats.objects.all():
        phone_number = phonenumbers.parse(str(flat.owners_phonenumber), 'RU')
        if phonenumbers.is_valid_number(phone_number):
            flat.owner_phone_pure=phone_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(filter_phonenumbers),
    ]
