# Generated by Django 2.2.4 on 2020-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200227_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='owner_deprecated',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(db_index=True,
                                         related_name='owner',
                                         to='property.Flat',
                                         verbose_name='Квартиры в собственности'),
        ),
    ]
