# Generated by Django 2.2.4 on 2020-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200227_1100'),
        ('property', '0011_auto_20200227_1100'),
    ]

    operations = [
    ]
